name: translation workflow

on:
  push:
    branches-ignore: [master]
    paths:
      - 'docs/**'

jobs:
  translate:
    environment: translations
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.variables.outputs.tag }}

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Checkout Devolutions/actions
        uses: actions/checkout@v4
        with:
          path: ./.github/workflows
          ref: v1
          repository: Devolutions/actions
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}

      - name: Install toolbox
        uses: ./.github/workflows/toolbox-install
        with:
          github_token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}

      - name: Download from onedrive
        uses: ./.github/workflows/onedrive-download
        with:
          azure_client_id: ${{ secrets.ONEDRIVE_AUTOMATION_CLIENT_ID }}
          azure_client_secret: ${{ secrets.ONEDRIVE_AUTOMATION_CLIENT_SECRET }}
          destination_path: ${{ runner.temp }}
          remote: releases
          source_path: /DevOps/Devolutions.ChatGPT.Cli

      - name: Add execute permission on Devolutions.ChatGPT.Cli
        run: chmod +x ${{ runner.temp }}/Devolutions.ChatGPT.Cli

      - name: Get changed files in specific folder
        run: |
          CURRENT_COMMIT=$(git rev-parse HEAD)
          LAST_COMMIT=$(git rev-parse HEAD~1)

          git diff --name-only $LAST_COMMIT $CURRENT_COMMIT -- docs/*/en/** > changed_files.txt
          echo "Changed files in docs/en:"
          cat changed_files.txt

      - name: Process each changed file
        run: |
          echo "Processing files listed in changed_files.txt"
          while IFS= read -r file; do
            echo "Processing $file"
            # Run your command-line application here
            ${{ runner.temp }}/Devolutions.ChatGPT.Cli "$file" ${{ secrets.ASSISTANT_API_KEY }} ${{ secrets.ASSISTANT_ID }}
          done < changed_files.txt

      - name: Commit translated files
        uses: ./.github/workflows/git-commit-and-push
        with:
          commit_message: Translations done by ChatGPT
          files: "docs/*/fr/**"
